### ISSUE TITLE
PartitionStrategyTest.shouldWriteToMultiplePartitions failling

### ISSUE THREAD

**Issue by pietermartin** [tinkerpop/tinkerpop3#501]
Hi,

Not entirely sure if this is a bug or rather my incorrect usage of steps and strategies.

This is on master branch.

I implement a `SqlgVertexStepStrategy`.

This replaces `VertexStep` with `SqlgVertexStep`

The reason for this is analogous to the `GraphStepStrategy` pattern for implementing `has step` logic.

For queries of the form,
```
List<Vertex> drivesBmw = marko.out("drives").<Vertex>has("name", "bmw").toList();
```
The SqlgVertexStep will cache the `HasContainer`s needed to construct a more optimal element retrieval query.

However with `PartitionStrategyTest.shouldWriteToMultiplePartitions` I am getting the following exception.
```
java.lang.ClassCastException: com.tinkerpop.gremlin.structure.strategy.StrategyVertex cannot be cast to org.umlg.sqlg.structure.SqlgVertex
	at org.umlg.sqlg.process.graph.util.SqlgVertexStep.lambda$new$0(SqlgVertexStep.java:35)
	at org.umlg.sqlg.process.graph.util.SqlgVertexStep$$Lambda$164/1028468265.apply(Unknown Source)
	at com.tinkerpop.gremlin.process.graph.step.map.FlatMapStep.processNextStart(FlatMapStep.java:40)
	at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
	at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.CountStep.processNextStart(CountStep.java:40)
	at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
	at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.SideEffectCapStep.standardAlgorithm(SideEffectCapStep.java:56)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.SideEffectCapStep.processNextStart(SideEffectCapStep.java:48)
	at com.tinkerpop.gremlin.process.util.AbstractStep.next(AbstractStep.java:102)
	at com.tinkerpop.gremlin.process.util.AbstractStep.next(AbstractStep.java:15)
	at com.tinkerpop.gremlin.process.util.DefaultTraversal.next(DefaultTraversal.java:97)
	at com.tinkerpop.gremlin.structure.strategy.PartitionStrategyTest.shouldWriteToMultiplePartitions(PartitionStrategyTest.java:194)
```

And the relevant code from `SqlgVertexStep`

```
    public SqlgVertexStep(final Traversal traversal, final Class<E> returnClass, final Direction direction, final String... edgeLabels) {
        super(traversal);
        this.direction = direction;
        this.edgeLabels = edgeLabels;
        this.returnClass = returnClass;
        if (Vertex.class.isAssignableFrom(this.returnClass))
            this.setFunction(traverser -> {
                if (this.hasContainers.isEmpty()) {
                    return (Iterator<E>) ((SqlgVertex)traverser.get()).vertices(Collections.emptyList(), this.direction, this.edgeLabels);
                } else {
                    return (Iterator<E>) ((SqlgVertex)traverser.get()).vertices(hasContainers, this.direction, this.edgeLabels);
                }
            });
        else
            this.setFunction(traverser -> (Iterator<E>) traverser.get().iterators().edgeIterator(this.direction, this.edgeLabels));
    }
```

So partition strategy is going throught the same call stack but the strategy needs the real `SqlgVertex` not the `StrategyVertex`.

Any advice on this one?
Thanks

**Comment by okram** [comment]
This is a known problem that @mbroecheler ran into with Titan. For TP3 M8, @spmallette is going to redesign how graph strategies are applied and hopefully remove the concept of `StrategyVertex` (wrapping a vertex).

**Comment by pietermartin** [comment]
Ok, thanks

**Comment by spmallette** [comment]
closing in favor of #516
