### ISSUE TITLE
UtilitiesGremlinPluginTest fails with Groovy 2.4.0

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#504]

**Comment by spmallette** [comment]
Seeing this as the exception when running from intellij.:

```text
[1m===>[m true

Assertion failed: 

assert name
       |
       ""

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:399)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:648)
	at org.codehaus.groovy.tools.shell.CommandRegistry.find(CommandRegistry.groovy:70)
	at org.codehaus.groovy.tools.shell.Shell.findCommand(Shell.groovy:76)
	at org.codehaus.groovy.tools.shell.Shell.findCommand(Shell.groovy)
	at org.codehaus.groovy.tools.shell.Shell.isExecutable(Shell.groovy:86)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
	at com.tinkerpop.gremlin.console.groovy.plugin.UtilitiesGremlinPluginTest$$Lambda$14/65551384.apply(Unknown Source)
	at com.tinkerpop.gremlin.console.groovy.plugin.SpyPluginAcceptor.eval(SpyPluginAcceptor.java:58)
	at com.tinkerpop.gremlin.console.groovy.plugin.UtilitiesGremlinPlugin.afterPluginTo(UtilitiesGremlinPlugin.java:42)
	at com.tinkerpop.gremlin.groovy.plugin.AbstractGremlinPlugin.pluginTo(AbstractGremlinPlugin.java:55)
	at com.tinkerpop.gremlin.console.groovy.plugin.UtilitiesGremlinPluginTest.shouldPluginUtilities(UtilitiesGremlinPluginTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
```

**Comment by spmallette** [comment]
This is fixed - or at least "worked around".  There is a bug in groovy-core it seems.  I've filed this issue:

https://jira.codehaus.org/browse/GROOVY-7290

basically, you can't do this in the console:

```text
gremlin> """test"""
assert name
      |
      ""
Display stack trace? [yN] 
```

meaning you can't start a line with the triple double quote which is an unlikely thing to do except when processing a multi-line script or something - in those cases,  you have to revert to old string concatenation until the bug is fixed.

**Comment by spmallette** [comment]
note that the utilities plugin works fine now was well:

```text
gremlin> describeGraph(TinkerGraph)
==>
IMPLEMENTATION - com.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph 
TINKERPOP TEST SUITE 
- Compliant with (8 of 8 suites) + 
> com.tinkerpop.gremlin.structure.StructureStandardSuite
> com.tinkerpop.gremlin.structure.StructurePerformanceSuite
> com.tinkerpop.gremlin.process.ProcessStandardSuite
> com.tinkerpop.gremlin.process.ProcessComputerSuite
> com.tinkerpop.gremlin.process.GroovyProcessStandardSuite
> com.tinkerpop.gremlin.process.GroovyProcessComputerSuite
> com.tinkerpop.gremlin.groovy.GroovyEnvironmentSuite
> com.tinkerpop.gremlin.groovy.GroovyEnvironmentIntegrateSuite 
- Opts out of 0 individual tests 
> none 
- NOTE - 
The describeGraph() function shows information about a Graph implementation. 
It uses information found in Java Annotations on the implementation itself to 
determine this output and does not assess the actual code of the test cases of 
the implementation itself.  Compliant implementations will faithfully and 
honestly supply these Annotations to provide the most accurate depiction of 
their support.
```
