### ISSUE TITLE
Encountered unregistered class ID

### ISSUE THREAD

**Issue by nik9000** [tinkerpop/tinkerpop3#517]
I'm using Titan built from its 09 branch to us Tinkerpop 3.0.0M7.  When I do this:
```
gremlin> :> g.V().has('wikibaseId', 'Q190804').in('P195').as('art').has('labelEn').out('P170').as('creator').has('labelEn').select().by('labelEn')
```

I get a lot of these:
```
io.netty.handler.codec.DecoderException: com.tinkerpop.gremlin.driver.ser.SerializationException: com.esotericsoftware.kryo.KryoException: Unable to find class: {art=Prince Maurits, accompanied by Prince Frederik Hendrik, Frederick V of Bohemia and his wife Elizabeth Stuart, and others, on the Buitenhof, The Hague, creator=Pauwels van Hillegaert}{art=The victory of the peasants, creator=Philips Wouwerman}
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at com.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:72)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tinkerpop.gremlin.driver.ser.SerializationException: com.esotericsoftware.kryo.KryoException: Unable to find class: {art=Prince Maurits, accompanied by Prince Frederik Hendrik, Frederick V of Bohemia and his wife Elizabeth Stuart, and others, on the Buitenhof, The Hague, creator=Pauwels van Hillegaert}{art=The victory of the peasants, creator=Philips Wouwerman}
	at com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.deserializeResponse(KryoMessageSerializerV1d0.java:153)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:29)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:17)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 20 more
Caused by: com.esotericsoftware.kryo.KryoException: Unable to find class: {art=Prince Maurits, accompanied by Prince Frederik Hendrik, Frederick V of Bohemia and his wife Elizabeth Stuart, and others, on the Buitenhof, The Hague, creator=Pauwels van Hillegaert}{art=The victory of the peasants, creator=Philips Wouwerman}
	at com.tinkerpop.gremlin.structure.io.kryo.GremlinClassResolver.readName(GremlinClassResolver.java:166)
	at com.tinkerpop.gremlin.structure.io.kryo.GremlinClassResolver.readClass(GremlinClassResolver.java:143)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
	at com.tinkerp
```
and these

```
io.netty.handler.codec.DecoderException: com.tinkerpop.gremlin.driver.ser.SerializationException: java.lang.IndexOutOfBoundsException: Index: 117, Size: 0
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at com.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:72)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tinkerpop.gremlin.driver.ser.SerializationException: java.lang.IndexOutOfBoundsException: Index: 117, Size: 0
	at com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.deserializeResponse(KryoMessageSerializerV1d0.java:153)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:29)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:17)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 20 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 117, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:42)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:805)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:759)
	at com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.deserializeResponse(KryoMessageSerializerV1d0.java:140)
	... 23 more
```

and these

```
2015-01-26 14:27:31 gremlin-driver-nio-1 WARN  tinkerpop.gremlin.driver.MessageSerializer - Response [UnpooledUnsafeDirectByteBuf(ridx: 995, widx: 995, cap: 995)] could not be deserialized by com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.
2015-01-26 14:27:31 gremlin-driver-nio-1 WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: com.tinkerpop.gremlin.driver.ser.SerializationException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 108
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at com.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:72)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tinkerpop.gremlin.driver.ser.SerializationException: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 108
	at com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.deserializeResponse(KryoMessageSerializerV1d0.java:153)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:29)
	at com.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:17)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 20 more
Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 108
	at com.tinkerpop.gremlin.structure.io.kryo.GremlinClassResolver.readClass(GremlinClassResolver.java:148)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:752)
	at com.tinkerpop.gremlin.driver.ser.KryoMessageSerializerV1d0.deserializeResponse(KryoMessageSerializerV1d0.java:140)
	... 23 more
```

It feels like something is picking up something half way through.

**Comment by nik9000** [comment]
I imagine this has something to do with changing maxContentLength.  I did that in a misguided attempt to fix something earlier.  The problem mostly went away when I undid that.

**Comment by spmallette** [comment]
Trying to isolate where this issue is coming from.  I assume that these are your client side errors that you've shown above.  In other words, none of these stack traces come from Gremlin Server, correct?

Also, could you alter your query a little bit, re-issue it and paste the results here:

```text
g.V().has('wikibaseId', 'Q190804').in('P195').as('art').has('labelEn').out('P170').as('creator').has('labelEn').select().by('labelEn').map{it.class}
```

**Comment by okram** [comment]
Where are we with this? I thought this was a non-issue (irreproducible) ?

**Comment by nik9000** [comment]
Sorry- I haven't had a chance to try it recently. You can close if you like
and I can reopen if I hit it again.

**Comment by spmallette** [comment]
My guess is that there might be some rough incompatibility between titan and TP3 at the point where this was tested.  Please feel free to reopen should it remain an issue.
