### ISSUE TITLE
cap() step leads to ConcurrentModificationException in TinkerGraph

### ISSUE THREAD

**Issue by jkschneider** [tinkerpop/tinkerpop3#526]
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at com.tinkerpop.gremlin.tinkergraph.process.graph.step.sideEffect.TinkerGraphStep.iteratorList(TinkerGraphStep.java:80)
	at com.tinkerpop.gremlin.tinkergraph.process.graph.step.sideEffect.TinkerGraphStep.vertices(TinkerGraphStep.java:54)
	at com.tinkerpop.gremlin.tinkergraph.process.graph.step.sideEffect.TinkerGraphStep.lambda$new$23(TinkerGraphStep.java:31)
	at com.tinkerpop.gremlin.tinkergraph.process.graph.step.sideEffect.TinkerGraphStep$$Lambda$20/2139741886.get(Unknown Source)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.GraphStep.generateTraversers(GraphStep.java:71)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.StartStep.processNextStart(StartStep.java:58)
	at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
	at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
	at com.tinkerpop.gremlin.process.graph.step.branch.RepeatStep.standardAlgorithm(RepeatStep.java:160)
	at com.tinkerpop.gremlin.process.graph.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:30)
	at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
	at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.SideEffectStep.processNextStart(SideEffectStep.java:28)
	at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
	at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.SideEffectCapStep.standardAlgorithm(SideEffectCapStep.java:56)
	at com.tinkerpop.gremlin.process.graph.step.sideEffect.SideEffectCapStep.processNextStart(SideEffectCapStep.java:48)
	at com.tinkerpop.gremlin.process.util.AbstractStep.next(AbstractStep.java:102)
	at com.tinkerpop.gremlin.process.util.AbstractStep.next(AbstractStep.java:15)
```

**Comment by jkschneider** [comment]
Should `vertices` in `TinkerGraph` be a `ConcurrentHashMap`?

**Comment by okram** [comment]
Can you provide more information? What was the traversal that triggered this? What version of TinkerPop3 are you using?

**Comment by jkschneider** [comment]
Sorry, this is 3.0.0-M7.  Attached is a somewhat simplified version of the query:

```java
g.V().has("org", id.getOrganization())
   .<Vertex>has("name", id.getName())
   .until(t -> !t.get().inE("depends").hasNext())
   .repeat(__.local(__
      .inE("depends")
      .<Edge>has("confs", /* predicate here */)
      .outV()
   ))
   .tree()
   .by((Vertex to) -> { /* some mapping */ })
   .<Tree<Downstream>>cap()
   .next();
```

**Comment by jkschneider** [comment]
Looks like it can only occur when `vertexIds.length == 0`:

```java
@Override
    public Iterator<Vertex> vertexIterator(final Object... vertexIds) {
        if (0 == vertexIds.length) {
            return this.vertices.values().iterator();
        } else if (1 == vertexIds.length) {
            final Vertex vertex = this.vertices.get(vertexIds[0]);
            return null == vertex ? Collections.emptyIterator() : IteratorUtils.of(vertex);
        } else
            return Stream.of(vertexIds).filter(this.vertices::containsKey).map(this.vertices::get).iterator();
    }
```

**Comment by okram** [comment]
Ah. Yea, seems I'm not wrapping the vertices in a new Collection. Eek, that will be expensive.... Hmmm...

**Comment by jkschneider** [comment]
No doubt.  That's why I hesitated to do a PR yet.  A `ConcurrentHashMap` for vertices should not be as expensive I think.

**Comment by okram** [comment]
Can't believe we didn't have a `GraphTest` test case for that. I added two new test cases (you can see in the commit). Finally, by using `ConcurrentHashMap` the tests passed. Actually, going to use concurrent structures elsewhere where I do array copies. 

Hope that helps ya.

**Comment by okram** [comment]
```java

**Comment by okram** [comment]
I was looking at your query. I think I have a fix so people don't have to `<Vertex>has()`. If you are using SNAPSHOT, your `until()` can be `until(__.inE("depends"))`. Finally, why do you do `local()` in your `repeat`? I think the result is the same regardless (but much faster without `local()`.

```java
g.V().has("org", id.getOrganization())
   .<Vertex>has("name", id.getName())
   .until(t -> !t.get().inE("depends").hasNext())
   .repeat(__.local(__
      .inE("depends")
      .<Edge>has("confs", /* predicate here */)
      .outV()
   ))
   .tree()
   .by((Vertex to) -> { /* some mapping */ })
   .<Tree<Downstream>>cap()
   .next();
```

**Comment by jkschneider** [comment]
Thanks for the quick work on this, Marko.  

* Good to know about until() -- that is an improvement.  
* I use local() because I don't want the intermediate edges to show up in the tree by() step, only the vertices.  
* Have you applied the same fix to cap() so I don't have to be explicit, i.e. `<Tree<Downstream>>cap()`?*

**Comment by okram** [comment]
I don't understand what is wrong with cap()? Wasn't this just a TinkerGraph bug?

**Comment by jkschneider** [comment]
Two distinct things about cap here:

1. The original issue regarding `ConcurrentModificationException`, which isn't really a cap problem, but this is the only place I have seen it manifest itself.  Anyway, you've fixed this now.
2.  cap()'s generic doesn't seem to observe the left-hand side of an expression, requiring an explicit cast, i.e.:

```Tree<Downstream> t = g.V(). /*...*/ .tree().by(t -> downstream(t)).<Tree<Downstream>>cap.next();```

**Comment by okram** [comment]
You can't go "one more deep" and get the free type cast. This works:

```java
Traversal<Vertex,Map<Integer,Long>> t = g.V().has(label,"person").groupCount().by("age").cap();
Map<Integer,Long> map = t.next()
```

If you know something I don't, please advise. Thanks.
