### ISSUE TITLE
Calling GraphTraversal.hasNext() causes AbstractMethodError in M7

### ISSUE THREAD

**Issue by dminkovsky** [tinkerpop/tinkerpop3#536]
TestController.java:
```
88:  GraphTraversal<Vertex, Vertex> titleTraversal = graph.V().has("hash", titleHash);
89:  Vertex vTitle = titleTraversal.hasNext() ? titleTraversal.next() : graph.addVertex( /* */ );
```

causes this trace:

```
Caused by: java.lang.AbstractMethodError: Method com/tinkerpop/gremlin/tinkergraph/structure/TinkerGraph.iterators()Lcom/tinkerpop/gremlin/structure/Graph$Iterators; is abstract
        at com.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.iterators(TinkerGraph.java)
        at com.tinkerpop.gremlin.process.graph.step.sideEffect.GraphStep.lambda$new$402(GraphStep.java:35)
        at com.tinkerpop.gremlin.process.graph.step.sideEffect.GraphStep$$Lambda$12/1464941093.get(Unknown Source)
        at com.tinkerpop.gremlin.process.graph.step.sideEffect.GraphStep.generateTraversers(GraphStep.java:71)
        at com.tinkerpop.gremlin.process.graph.step.sideEffect.StartStep.processNextStart(StartStep.java:58)
        at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
        at com.tinkerpop.gremlin.process.util.ExpandableStepIterator.next(ExpandableStepIterator.java:33)
        at com.tinkerpop.gremlin.process.graph.step.filter.FilterStep.processNextStart(FilterSte28)ava:
        at com.tinkerpop.gremlin.process.util.AbstractStep.hasNext(AbstractStep.java:117)
        at com.tinkerpop.gremlin.process.util.DefaultTraversal.hasNext(DefaultTraversal.java:87)
        at test.controller.TestController.postTest(TestController.java:89)
```

Didn't happen with M6. I thought maybe the API changed, but I'm using `V()` and otherwise the API looks the same here. A bug?

**Comment by dminkovsky** [comment]
Whoops I updated tinkerpop but left tinkergraph at M6.
