### ISSUE TITLE
Gremlin Console / Server: remote graph cannot be serialized

### ISSUE THREAD

**Issue by rutgervanwilligen** [tinkerpop/tinkerpop3#563]
If the console connects to a remote gremlin server with `conf/remote.yaml` configuration, the command `:> g` results in a satisfactory output. This does not work, however, when `conf/remote-objects.yaml` is used. This holds for both M7 and SNAPSHOT.

Output when using `conf/remote.yaml`:

```
$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install com.tinkerpop neo4j-gremlin 3.0.0-SNAPSHOT
==>A module with the name neo4j-gremlin is already installed
gremlin> :plugin use tinkerpop.neo4j
==>tinkerpop.neo4j activated
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :> g
==>neo4jgraph[EmbeddedGraphDatabase [/tmp/neo4j]]
gremlin>
```

Output when using `conf/remote-objects.yaml`:

```
$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install com.tinkerpop neo4j-gremlin 3.0.0-SNAPSHOT
==>A module with the name neo4j-gremlin is already installed
gremlin> :plugin use tinkerpop.neo4j
==>tinkerpop.neo4j activated
gremlin> :remote connect tinkerpop.server conf/remote-objects.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :> g.V()
==>v[0]
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
gremlin> :> g
WARN  io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at com.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:45)
	at com.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at com.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:72)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Server could not serialize the result requested. Server error - Error during serialization: Class is not registered: com.tinkerpop.gremlin.neo4j.structure.Neo4jGraph
Note: To register this class use: kryo.register(com.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.class);. Note that the class must be serializable by the client and server for proper operation.
Display stack trace? [yN] y
com.tinkerpop.gremlin.groovy.plugin.RemoteException: Server could not serialize the result requested. Server error - Error during serialization: Class is not registered: com.tinkerpop.gremlin.neo4j.structure.Neo4jGraph
Note: To register this class use: kryo.register(com.tinkerpop.gremlin.neo4j.structure.Neo4jGraph.class);. Note that the class must be serializable by the client and server for proper operation.
	at com.tinkerpop.gremlin.console.groovy.plugin.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:92)
	at com.tinkerpop.gremlin.console.commands.SubmitCommand.execute(SubmitCommand.groovy:23)
	at org.codehaus.groovy.tools.shell.Shell.execute(Shell.groovy:101)
	at org.codehaus.groovy.tools.shell.Groovysh.super$2$execute(Groovysh.groovy)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1208)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
	at org.codehaus.groovy.tools.shell.Groovysh.executeCommand(Groovysh.groovy:254)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:153)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:119)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:94)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1208)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:123)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:58)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1208)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:82)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
	at com.tinkerpop.gremlin.console.Console.<init>(Console.groovy:95)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
	at com.tinkerpop.gremlin.console.Console.main(Console.groovy:248)
gremlin> 
```

**Comment by spmallette** [comment]
The stack trace is kinda gross.  We probably should unwrap serialization exceptions, as they will be common, and show a better message.  I think that will be the resulting enhancement here.

As far as being able to serialize an entire `Graph` instance, it's is unlikely we will support that.  I don't think that is a use case for "remoting".  It's no different than writing some SQL that asked for the entire database to be sent back.  When you write a remote query/SQL you try to limit your results as best you can to just what you want.  That is the use case remoting seeks to satisfy.  I would say that if you must send back an entire `Graph` (maybe you are dealing with lots of small in-memory instances or subgraphs), then pipe them out to kryo via the `g.io()` methods, and read that into a local `Graph` on your remote side.

**Comment by rutgervanwilligen** [comment]
Yep, I agree. Cheers for the enhancement filing!

**Comment by spmallette** [comment]
After digging into this, the error looks more severe that what it really should be because of the underlying netty logger.  I tweak the configuration to turn that off which got rid of the first ugly stack trace which leaves the output looking more like this when the error appears:

```text
gremlin> :> g
Server could not serialize the result requested. Server error - Error during serialization: Class is not registered: org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph
Note: To register this class use: kryo.register(org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.class);. Note that the class must be serializable by the client and server for proper operation.
Display stack trace? [yN] n
```

That's a pretty clear explanation as to what the problem is i think - will leave it at that.
